Heroku setup
CourseFlo/Flo pull request #29
Opened 2020-07-19 04:22 UTC by DSep

Prepared and pushed this code for deployment to heroku.

Review and make changes if you'd like a different method of deployment, and be sure to test by deploying.

2020-07-19 14:01 UTC, beetai requested changes
all this looks good, just a couple small changes and we can test em out.
nice going, @DSep deployment G O D

i should also add that i'm fine with placing the frontend within the server (also did this with my assignment xd), so i'm down to keep it like that
commits can be squashed, sounds good to me

2020-07-19 14:01 UTC, beetai commented on server/app.js
> +app.use(express.static(path.join(__dirname, 'frontend', 'build')));
This should be under an if statement, (`if (NODE_ENV === 'production')`)

2020-07-19 14:01 UTC, beetai commented on server/app.js
> +// if (process.env.NODE_ENV === 'production') {
I think we should put this if statement back and remove 404 error handling that is automatically generated by express-generator

2020-07-19 14:01 UTC, beetai commented on server/app.js
> +});
same as above, place in if statement

2020-07-19 14:01 UTC, beetai commented on server/frontend/package.json
> +  "proxy": "http://localhost"
i think we can specify the development port here (9000)

2020-07-19 14:01 UTC, beetai commented on server/package.json
> +    "heroku-postbuild": "cd frontend && npm install && npm run build"
i think this looks good to me.
Though I do want to ask what `DEBUG=express-locallibrary-tutorial:*` is about?

2020-07-20 21:36 UTC, DSep commented on server/frontend/package.json
> +  "proxy": "http://localhost"
Yep

2020-07-20 21:45 UTC, DSep commented on server/package.json
> +    "heroku-postbuild": "cd frontend && npm install && npm run build"
nodemon config, from the express server setup. Could be changed to a different name

2020-07-20 21:45 UTC, DSep commented on server/app.js
> +app.use(express.static(path.join(__dirname, 'frontend', 'build')));
Why?

2020-07-20 22:12 UTC, DSep commented on server/app.js
> +// if (process.env.NODE_ENV === 'production') {
Why?

2020-07-20 22:12 UTC, DSep commented on server/app.js
> +});
Why?

2020-07-21 07:06 UTC, beetai commented on server/app.js
> +app.use(express.static(path.join(__dirname, 'frontend', 'build')));
in order to distinguish between development and production. when developing, we should not be running everything on a single server

2020-07-21 07:07 UTC, yqj2k approved these changes
This helped me finish the assignment on time. Bless

2020-07-21 07:08 UTC, beetai commented on server/app.js
> +// if (process.env.NODE_ENV === 'production') {
removing the error handling fixes the issue of not properly directing to frontend code

2020-07-21 07:08 UTC, beetai commented on server/app.js
> +});
same as first comment

2020-07-22 02:43 UTC, baconandchips commented
Praise be the coding god

2020-07-22 02:44 UTC, baconandchips approved these changes

2020-07-22 05:10 UTC, baconandchips approved these changes

2020-07-22 05:10 UTC, baconandchips commented on server/app.js
> +// if (process.env.NODE_ENV === 'production') {
Frontend code appears to be prioritized for displaying when lines 29 and 30, currently:
```
app.use(express.static(path.join(__dirname, 'public')));
app.use(express.static(path.join(__dirname, 'frontend', 'build')));

```
is above line 42, which is the beginning of the backend routing:
`app.use('/', indexRouter);`

I'm pretty sure you got this already, but just in case, I wanted to put it here too

2020-07-22 05:18 UTC, beetai approved these changes
kool

2020-07-22 05:20 UTC, merged