redux refactor profile page
CourseFlo/Flo pull request #30
Opened 2020-07-22 06:59 UTC by beetai

galaxy brain sepand strikes again

2020-07-22 07:17 UTC, DSep requested changes
Let's see if we can avoid having the editing flags in the redux store.

2020-07-22 07:17 UTC, DSep commented on frontend/src/redux/reducers/Profile.tsx
> +};
Can we just get rid of this state?

2020-07-22 07:17 UTC, DSep commented on frontend/src/components/ProtectedRoute.tsx
> +  // }
just comments that can be removed

2020-07-22 07:17 UTC, DSep commented on frontend/src/type-interfaces/FieldEditState.tsx
> +}
Cool, but possibly overkill? At least as something in the store. Could use in local state instead

2020-07-22 07:17 UTC, DSep commented on frontend/src/redux/actions/Profile.tsx
> +});
Let's figure out if we can avoid this being an action

2020-07-22 07:17 UTC, DSep commented on frontend/src/pages/AccountForm.tsx
> +    setField('major', false);
Let's try and do this locally

2020-07-23 00:19 UTC, DSep commented on frontend/src/pages/AccountForm.tsx
> +
More comments

2020-07-23 00:49 UTC, baconandchips commented on frontend/src/redux/reducers/User.tsx
> +      return action.users[0];
Will this be changed in the future? It seems to currently grab the first user only. Otherwise LGTM

2020-07-23 01:03 UTC, yqj2k approved these changes

2020-07-23 01:04 UTC, baconandchips commented on frontend/src/redux/reducers/User.tsx
> +      return action.users[0];
Add(ed) to card, tbd; perhaps in future

2020-07-23 01:07 UTC, DSep requested changes

2020-07-23 01:07 UTC, DSep commented on frontend/src/redux/reducers/User.tsx
> +    case 'GET_USERS':
Make into constant pls

2020-07-23 01:10 UTC, baconandchips commented on frontend/src/redux/actions/User.tsx
> +  type: 'UPDATE_USER',
constant as well

2020-07-23 01:12 UTC, DSep approved these changes
LGTM now

2020-07-23 01:12 UTC, merged